name: Test on github runner
on:
  pull_request:
  push: { branches: main }

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"

    name: Run test suite
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pytest

      - name: Run tests
        run: echo "test done"
